# allow-anonymous-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-anonymous
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin   # or create a custom read-only role
subjects:
  - kind: User
    name: system:anonymous
    apiGroup: rbac.authorization.k8s.io
