apiVersion: v1
kind: Pod
metadata:
  name: root-pod
spec:
  containers:
  - name: root-container
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 60; done"]
    securityContext:
      runAsUser: 0
